name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    run-on: ubuntu-20.04
    steps:
      - name: say hello
        run: |
          echo "Hello world"
